---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: /etc/yum.repos.d/open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: AppServers
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - AppServer

- name: Front End Servers
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - FEServer

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - DbServer
