  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: enable postgresql at boot
    service:
      name: postgresql
      enabled: yes
#  - name: tell user to finish setting up postgres
#    debug:
#      msg: "Either uncomment the postgres setup or manually login and initialize"

# only run the next 2 tasks once!
#  - name: initialize postgres
#    command: postgresql-setup initdb
  - name: initialize postgres some more
    command: chkconfig postgresql on
  - name: start postgres
    service:
      name: postgresql.service
      state: started
